In [2]:
import numpy as np
import pandas as pd

In [41]:
array1=np.array([1,3,5,7,9],dtype=int)
df=pd.DataFrame(array1)
print("DataFrame  1 :- \n",df)
#df=pd.read_csv(r"C:\Users\Lab\Desktop\2470046_Amritanshu\Student Performance 1.csv")

array2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
df1=pd.DataFrame(array2)
print("\nDataFrame 2 :- \n",df1)

array3=np.arange(5,15,1).reshape(2,5)
df3=pd.DataFrame(array3)
print("\nData Frame 3 :- \n",df3)

print("\narray3[0][0] :- ",array3[0][0]) # or array3[0,0]


print("\ndf3[0][0] :- ",df3[0][0])

#print("\ndf3[0:0] :- \n",df3[0:1])

print("\ndf3.loc[0,0] :- ",df3.loc[0,0])
print("\ndf3.iloc[1,1] :- ",df3.iloc[1,1])

DataFrame  1 :- 
    0
0  1
1  3
2  5
3  7
4  9

DataFrame 2 :- 
    0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

Data Frame 3 :- 
     0   1   2   3   4
0   5   6   7   8   9
1  10  11  12  13  14

array3[0][0] :-  5

df3[0][0] :-  5

df3.loc[0,0] :-  5

df3.iloc[1,1] :-  11


# Exploring Iris Dataset

In [9]:
from sklearn.datasets import load_iris

Iris = load_iris()

In [94]:
print("Iris data :- ",Iris.data)
print("\nrows & column :- ",Iris.data.shape)

Iris data :-  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5

In [6]:
print("Iris.target :- \n",Iris.target)
print("\nsize :- ",Iris.target.size)

Iris.target :- 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]

size :-  150


In [54]:
Iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [58]:
data=pd.DataFrame(data=Iris.data,columns=Iris.feature_names)
data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [10]:
data1=pd.DataFrame(data=Iris.data,columns=Iris.feature_names)
data1['target']=Iris.target
data1

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [70]:
data1.head(10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   
5                5.4               3.9                1.7               0.4   
6                4.6               3.4                1.4               0.3   
7                5.0               3.4                1.5               0.2   
8                4.4               2.9                1.4               0.2   
9                4.9               3.1                1.5               0.1   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  
5       0  
6       0  
7       0  
8       0  
9       0

In [78]:
print("data1[45:50] :- ",data1[45:55])
print("\ndata1[51,60] :-  ",data1[51:60])
print("\ndata1[95:100] :- ",data1[95:100])
print("\ndata1[101:105] :- ",data1[101:105])
print("\ndata1[145:150] :- ",data1[145:150])

data1[45:50] :-      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
45                4.8               3.0                1.4               0.3   
46                5.1               3.8                1.6               0.2   
47                4.6               3.2                1.4               0.2   
48                5.3               3.7                1.5               0.2   
49                5.0               3.3                1.4               0.2   
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   
52                6.9               3.1                4.9               1.5   
53                5.5               2.3                4.0               1.3   
54                6.5               2.8                4.6               1.5   

    target  
45       0  
46       0  
47       0  
48       0  
49       0  
50       1  
51       1 

In [79]:
#suffle the rows
data1.sample(n=5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
27                 5.2               3.5                1.5               0.2   
125                7.2               3.2                6.0               1.8   
73                 6.1               2.8                4.7               1.2   
77                 6.7               3.0                5.0               1.7   
4                  5.0               3.6                1.4               0.2   

     target  
27        0  
125       2  
73        1  
77        1  
4         0

In [85]:
data1.sample(frac=1)
shuffled_data = data1.sample(frac=0.5)
shuffled_data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
107                7.3               2.9                6.3               1.8   
3                  4.6               3.1                1.5               0.2   
130                7.4               2.8                6.1               1.9   
105                7.6               3.0                6.6               2.1   
46                 5.1               3.8                1.6               0.2   
..                 ...               ...                ...               ...   
76                 6.8               2.8                4.8               1.4   
135                7.7               3.0                6.1               2.3   
120                6.9               3.2                5.7               2.3   
47                 4.6               3.2                1.4               0.2   
49                 5.0               3.3                1.4               0.2   

     target  
107       2  
3         0  
130       2  
105       2  
46        0  
..      ...  
76        1  
135       2  
120       2  
47        0  
49        0  

[75 rows x 5 columns]

In [89]:
shuffled_data=data1.sample(frac=1).reset_index(drop=True)
shuffled_data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.5               2.4                3.7               1.0   
1                  6.2               2.9                4.3               1.3   
2                  6.2               2.2                4.5               1.5   
3                  5.8               2.7                3.9               1.2   
4                  5.4               3.9                1.7               0.4   
..                 ...               ...                ...               ...   
145                5.4               3.0                4.5               1.5   
146                5.7               2.6                3.5               1.0   
147                5.4               3.9                1.3               0.4   
148                5.1               3.5                1.4               0.2   
149                6.0               2.9                4.5               1.5   

     target  
0         1  
1         1  
2         1  
3         1  
4         0  
..      ...  
145       1  
146       1  
147       0  
148       0  
149       1  

[150 rows x 5 columns]

In [11]:
versicular=data1[0:50]
verginica=data1[50:100]
stosa=data1[100:150]
print("Versicular class : \n",versicular)
print("\nVerginica class : \n",verginica)
print("\nStosa class : ",stosa)

Versicular class : 
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
5                 5.4               3.9                1.7               0.4   
6                 4.6               3.4                1.4               0.3   
7                 5.0               3.4                1.5               0.2   
8                 4.4               2.9                1.4               0.2   
9                 4.9               3.1                1.5               0.1   
10                5.4               3.7                1.5               0.2   
11                4

In [12]:
suffled_data=versicular.sample(frac=1)
suffled_data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
15                5.7               4.4                1.5               0.4   
33                5.5               4.2                1.4               0.2   
24                4.8               3.4                1.9               0.2   
35                5.0               3.2                1.2               0.2   
30                4.8               3.1                1.6               0.2   
19                5.1               3.8                1.5               0.3   
44                5.1               3.8                1.9               0.4   
29                4.7               3.2                1.6               0.2   
39                5.1               3.4                1.5               0.2   
8                 4.4               2.9                1.4               0.2   
0                 5.1               3.5                1.4               0.2   
41                4.5               2.3                1.3               0.3   
37                4.9               3.6                1.4               0.1   
7                 5.0               3.4                1.5               0.2   
1                 4.9               3.0                1.4               0.2   
26                5.0               3.4                1.6               0.4   
12                4.8               3.0                1.4               0.1   
36                5.5               3.5                1.3               0.2   
16                5.4               3.9                1.3               0.4   
28                5.2               3.4                1.4               0.2   
49                5.0               3.3                1.4               0.2   
6                 4.6               3.4                1.4               0.3   
9                 4.9               3.1                1.5               0.1   
48                5.3               3.7                1.5               0.2   
5                 5.4               3.9                1.7               0.4   
3                 4.6               3.1                1.5               0.2   
40                5.0               3.5                1.3               0.3   
22                4.6               3.6                1.0               0.2   
13                4.3               3.0                1.1               0.1   
38                4.4               3.0                1.3               0.2   
31                5.4               3.4                1.5               0.4   
45                4.8               3.0                1.4               0.3   
34                4.9               3.1                1.5               0.2   
42                4.4               3.2                1.3               0.2   
27                5.2               3.5                1.5               0.2   
25                5.0               3.0                1.6               0.2   
21                5.1               3.7                1.5               0.4   
46                5.1               3.8                1.6               0.2   
47                4.6               3.2                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
32                5.2               4.1                1.5               0.1   
43                5.0               3.5                1.6               0.6   
14                5.8               4.0                1.2               0.2   
4                 5.0               3.6                1.4               0.2   
10                5.4               3.7                1.5               0.2   
23                5.1               3.3                1.7               0.5   
20                5.4               3.4                1.7               0.2   
11                4.8               3.4                1.6               0.2   
17                5.1               3.5                1.4               0.3   
18  