In [2]:
import numpy as np

In [4]:
arr=np.array([[1,2,3],[4,5,6]])

In [6]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
ar1=np.arange(10)
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
ar2=np.arange(5,20,3)
ar2

array([ 5,  8, 11, 14, 17])

In [19]:
ar3=np.arange(6).reshape(3,2)
ar3

array([[0, 1],
       [2, 3],
       [4, 5]])

In [25]:
ar4=np.arange(20).reshape(5,2,2)
ar4

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])