In [54]:
import numpy as np

In [56]:
import pandas as pd

In [58]:
arr=np.array([[1,2,3],[4,5,6]])

In [60]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
ar2=np.arange(6).reshape(2,3)
ar2

array([[0, 1, 2],
       [3, 4, 5]])

In [64]:
ar4=np.arange(30).reshape(3,2,5)
ar4

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [66]:
A=np.arange(20)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [68]:
print(A.reshape(4,5))
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [82]:
print(A.shape)
print(A.ndim)
print(A.dtype)
print(A.size)
print(A.itemsize)
#print(A.size[axis=0])
print(np.size(A, axis=0))
print(A.shape[0])
print(np.zeros((3,4)))

(20,)
1
int64
20
8
20
20
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
